services:
  backend:
    build: .
    ports:
      - "8888:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33060:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"